travis:
  secure:
    BINSTAR_TOKEN: hk5pvSuE5ph0mOd1yUcwZe3XUaq5nCFdxeqJ2jdSwJMOuwZ8CMp1YwfzKxTXmzvyPx1DKKfZANn0SHSgZOVEtSxtxTCk3/+qeNHwvUOSJ469FGojDsw9j9BUB7jV5BZN3xjR6pUtyxTuiRyYxsj1EHLqY4b95au7NnRmcksoVMbVZbIbqipRunvQSklI5v4Jrr4V5i58CCb/YCv+GJ9u0LOe2SZaWULiPrr1lDXI4bxbBAkxtxhvlQ0+Ik5deENmamBtn6Y8vGjeZ70AxHVFfZX2b1+LtOLeN4QpALvS0dwryfKLvlLsLpe8d6bDDwQxxD90uuE4gQCTYTG7r/YGn/2DBI6R98QUKmgoNgu6bs0sl0G3LeXYVyeOEIZgsxGDfU2XywW6FX5EPs1hATFdbJN9I3j9QJ1uGs8K5Vlfpo/zY4lRfEeIh5nSkt2m87/no/z5ZTWmx6ZVDmqvKSsN5eJBdBaGBBu6IL4Qm2rwho3aXf3nqcRcLcfEN2TYzs5xT5Qftil4TK2b7TmrV4sB1nPGdj351aFJb0vRFeYLElNUVnLmS7jwQ2YiqmZMoSIcpZv6QCzRD6kskgmPb5tDSBlixsXACUVzyzlW8NdmIXGYbsonLO3jZXR/YoccMkvItfM9+4f2uCwGNFFoAwCA0JFqMFduvPOzBIrwHBX6gZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
